/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT
	country,
	COUNT(customer_id) AS customers_by_countries
FROM gold.dim_customers
GROUP BY country
ORDER BY customers_by_countries DESC

-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_id) AS customeres_by_gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY customeres_by_gender DESC

-- Find total products by category
SELECT
	product_category,
	COUNT(product_category) AS total_category
FROM gold.dim_products
GROUP BY product_category
ORDER BY total_category DESC

-- What is the average costs in each category?
SELECT
	product_category,
	AVG(CAST(product_cost AS INT)) AS average_cost
FROM gold.dim_products
GROUP BY product_category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category?
SELECT
	DP.product_category,
	SUM(FS.sales_amount) AS category_revenue 
FROM  gold.fact_sales FS 
LEFT JOIN gold.dim_products DP ON FS.product_key = DP.product_key
GROUP BY DP.product_category
ORDER BY category_revenue DESC

-- What is the total revenue generated by each customer?
SELECT
	DC.customer_key,
	DC.first_name,
	DC.last_name,
	SUM(FS.sales_amount) AS revenue_customer
FROM gold.fact_sales FS
LEFT JOIN gold.dim_customers DC ON FS.customer_key = DC.customer_key
GROUP BY DC.customer_key, DC.first_name, DC.last_name
ORDER BY revenue_customer DESC

-- What is the distribution of sold items across countries?
SELECT 
	DM.country,
	SUM(FS.quantity) AS total_country
FROM gold.fact_sales FS
LEFT JOIN gold.dim_customers DM ON FS.customer_key = DM.customer_key
GROUP BY country
ORDER BY total_country DESC

